; generado a partir del sprite 16x16 del usuario (mk manual)
; 0=transparente 1=piel 2=marron 3=negro
dollA_p0:
    .byte $00, $00, $0F, $1F, $1F, $1F, $07, $01
dollA_p1:
    .byte $07, $0F, $0E, $14, $16, $18, $00, $0F
dollB_p0:
    .byte $00, $00, $E0, $F8, $FC, $F0, $F0, $00
dollB_p1:
    .byte $C0, $FE, $40, $40, $20, $F0, $00, $C0
dollC_p0:
    .byte $01, $01, $33, $38, $30, $00, $1C, $3C
dollC_p1:
    .byte $1F, $3F, $0E, $07, $0F, $0E, $1C, $3C
dollD_p0:
    .byte $10, $10, $39, $07, $07, $00, $38, $3C
dollD_p1:
    .byte $FE, $FF, $CE, $F8, $F8, $70, $38, $3C
